version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    expose:
      - 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
